import { useEffect, useMemo, useState } from 'react';
import { createCoverThumbnail, extractCoverPalette, type CoverPalette } from '../cover-palette';
import { getCatalogTracks } from '../services/catalog-api';
import { AlbumAdminError, createAdminAlbum, deleteAdminAlbumAsset, getAdminAlbum, getAdminAlbums, moveAdminAlbumTrack, saveAdminAlbumMembership, saveAdminAlbumMetadata, uploadAdminAlbumAsset, type AdminAlbumAssetState, type AdminAlbumManifest, type AdminAlbumMetadataPatch, type AdminAlbumStatus, type AdminAlbumSummary, type AdminAlbumType } from '../services/album-admin-api';
import type { StudioTrack } from '../types/studio';
import { CoverImagePreview } from './CoverImagePreview';
import { CoverPalettePreview } from './CoverPalettePreview';

type Form = { title:string; type:AdminAlbumType; status:AdminAlbumStatus; year:string; releaseDate:string; description:string; heading:string; accent:string; accent2:string };
const EMPTY: Form = { title:'', type:'album', status:'draft', year:'', releaseDate:'', description:'', heading:'', accent:'', accent2:'' };
const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
const formFrom=(a:AdminAlbumManifest):Form=>({title:a.title||'',type:a.type,status:a.status,year:a.year?String(a.year):'',releaseDate:a.releaseDate?.slice(0,10)||'',description:a.description||'',heading:a.heading||'',accent:a.accent||'',accent2:a.accent2||''});
function patch(f:Form):AdminAlbumMetadataPatch { const y=f.year.trim()?Number(f.year):null; if(f.year.trim()&&(!Number.isInteger(y)||y!<1000||y!>9999)) throw new AlbumAdminError('Album year must be a four-digit year.'); return {title:f.title.trim(),type:f.type,status:f.status,year:y,releaseDate:f.releaseDate||null,description:f.description.trim()||null,heading:f.heading.trim()||null,accent:f.accent.trim()||null,accent2:f.accent2.trim()||null}; }
function err(x:unknown){ if(x instanceof AlbumAdminError) return `${x.message}${x.code?` [${x.code}]`:''}${x.currentUpdatedAt?` Canonical revision is now ${x.currentUpdatedAt}.`:''}`; return x instanceof Error?x.message:String(x); }
const badge=(a:AdminAlbumManifest)=>`${a.type.toUpperCase()} · ${a.status.toUpperCase()}`;

function AlbumCreatePanel({onCreated,onCancel}:{onCreated:(id:string)=>Promise<void>;onCancel:()=>void}){
  const [title,setTitle]=useState(''); const [id,setId]=useState(''); const [type,setType]=useState<AdminAlbumType>('album'); const [year,setYear]=useState(''); const [releaseDate,setReleaseDate]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const effective=id.trim()||slugify(title); const valid=Boolean(title.trim()&&/^[a-z0-9][a-z0-9-]{0,119}$/.test(effective));
  async function create(){ if(!valid||busy)return; if(!globalThis.confirm(`Create canonical ${type.toUpperCase()} draft “${title.trim()}”?\n\nThis writes albums/${effective}/manifest.json through Track Manager v5.17. No legacy Album is migrated.`))return; setBusy(true);setError(null); try{ const y=year.trim()?Number(year):null;if(year.trim()&&(!Number.isInteger(y)||y!<1000||y!>9999))throw new AlbumAdminError('Album year must be a four-digit year.'); const r=await createAdminAlbum({id:effective,title:title.trim(),type,year:y,releaseDate:releaseDate||null}); if(!r.clientVerified)throw new AlbumAdminError(r.verificationWarning||'Album create could not be canonically verified.'); await onCreated(effective);}catch(x){setError(err(x))}finally{setBusy(false)} }
  return <section className="panel album-create-panel"><div className="album-section-head"><div><span className="eyebrow">NEW CANONICAL RELEASE</span><h3>Create an Album / EP draft</h3><p>The ID becomes immutable after creation. This never migrates legacy release data.</p></div><button className="ghost-btn compact" disabled={busy} onClick={onCancel}>Close</button></div><div className="album-form-grid"><label><span>Title <b>Required</b></span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>Canonical ID <b>Immutable</b></span><input value={id} onChange={e=>setId(slugify(e.target.value))} placeholder={slugify(title)||'album-id'}/></label><label><span>Type</span><select value={type} onChange={e=>setType(e.target.value as AdminAlbumType)}><option value="album">Album</option><option value="ep">EP</option><option value="collection">Collection</option></select></label><label><span>Year</span><input inputMode="numeric" value={year} onChange={e=>setYear(e.target.value)}/></label><label><span>Release date</span><input type="date" value={releaseDate} onChange={e=>setReleaseDate(e.target.value)}/></label></div><div className="album-actions"><button className="ghost-btn" disabled={busy} onClick={onCancel}>Cancel</button><button className="primary-btn" disabled={!valid||busy} onClick={()=>void create()}>{busy?'Creating…':'Create canonical draft'}</button></div>{error&&<div className="album-error">{error}</div>}</section>;
}

function AlbumEditor({albumId,albums,tracks,onChanged,onClose}:{albumId:string;albums:AdminAlbumSummary[];tracks:StudioTrack[];onChanged:()=>Promise<void>;onClose:()=>void}){
  const [album,setAlbum]=useState<AdminAlbumManifest|null>(null); const [assets,setAssets]=useState<Partial<Record<'cover'|'thumbnail',AdminAlbumAssetState|null>>>({}); const [form,setForm]=useState<Form>(EMPTY); const [ids,setIds]=useState<string[]>([]); const [moves,setMoves]=useState<Record<string,string>>({}); const [cover,setCover]=useState<File|null>(null); const [palette,setPalette]=useState<CoverPalette|null>(null); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
  async function load(){setLoading(true);try{const p=await getAdminAlbum(albumId);const a=p.album?.manifest;if(!a)throw new Error('Canonical Album manifest is missing.');setAlbum(a);setForm(formFrom(a));setIds([...a.trackIds]);setAssets(p.album?.assets||{});setError(null)}catch(x){setError(err(x))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[albumId]); useEffect(()=>{if(!cover){setPalette(null);return}let live=true;extractCoverPalette(cover).then(v=>live&&setPalette(v)).catch(()=>live&&setPalette(null));return()=>{live=false}},[cover]);
  const byId=useMemo(()=>new Map(tracks.map(t=>[t.id,t])),[tracks]); const changed=album?JSON.stringify(ids)!==JSON.stringify(album.trackIds):false;
  async function mutate(task:()=>Promise<void>){if(busy)return;setBusy(true);setError(null);setNotice(null);try{await task();await load();await onChanged()}catch(x){setError(err(x));await load().catch(()=>{})}finally{setBusy(false)}}
  async function saveMetadata(){if(!album?.updatedAt)return;await mutate(async()=>{const r=await saveAdminAlbumMetadata(album.id,album.updatedAt!,patch(form));if(!r.clientVerified)throw new AlbumAdminError(r.verificationWarning||'Album metadata reread failed.');setNotice('Album metadata saved and canonically reread.')})}
  async function saveTracklist(){if(!album?.updatedAt||!changed)return;if(!globalThis.confirm(`Save ordered tracklist for “${album.title}”?\n\nRemoved tracks return to the transitional Singles cache.`))return;await mutate(async()=>{const r=await saveAdminAlbumMembership(album.id,album.updatedAt!,ids);if(!r.clientVerified)throw new AlbumAdminError(r.verificationWarning||'Album tracklist reread failed.');setNotice('Album tracklist saved and canonically reread.')})}
  async function move(trackId:string){if(!album)return;const targetId=moves[trackId],targetSummary=albums.find(a=>a.id===targetId);if(!targetId||!targetSummary)return;if(!globalThis.confirm(`Move “${byId.get(trackId)?.title||trackId}” to “${targetSummary.title}”?\n\nTrack Manager updates source + target in one transaction.`))return;await mutate(async()=>{const [s,t]=await Promise.all([getAdminAlbum(album.id),getAdminAlbum(targetId)]);const source=s.album?.manifest,target=t.album?.manifest;if(!source?.updatedAt||!target?.updatedAt)throw new AlbumAdminError('Fresh source/target revisions unavailable.');const r=await moveAdminAlbumTrack(targetId,{trackId,sourceAlbumId:album.id,expectedSourceUpdatedAt:source.updatedAt,expectedTargetUpdatedAt:target.updatedAt,targetIndex:target.trackIds.length});if(!r.clientVerified)throw new AlbumAdminError(r.verificationWarning||'Album move reread failed.');setNotice('Track moved and canonically reread.')})}
  async function upload(){if(!album?.updatedAt||!cover)return;await mutate(async()=>{let rev=album.updatedAt!;const a=await uploadAdminAlbumAsset(album.id,'cover',rev,cover);if(!a.clientVerified||!a.updatedAt)throw new AlbumAdminError(a.verificationWarning||'Cover reread failed.');rev=a.updatedAt;const thumb=await createCoverThumbnail(cover);const b=await uploadAdminAlbumAsset(album.id,'thumbnail',rev,thumb);if(!b.clientVerified)throw new AlbumAdminError(b.verificationWarning||'Thumbnail reread failed.');setCover(null);setNotice('Album cover + thumbnail uploaded sequentially and reread.')})}
  async function removeAsset(kind:'cover'|'thumbnail'){if(!album?.updatedAt||!assets[kind]?.present)return;if(!globalThis.confirm(`Delete canonical Album ${kind}?\n\nThis is guarded with backup + rollback. Whole-Album deletion is unavailable.`))return;await mutate(async()=>{const r=await deleteAdminAlbumAsset(album.id,kind,album.updatedAt!);if(!r.clientVerified)throw new AlbumAdminError(r.verificationWarning||`${kind} reread failed.`);setNotice(`Album ${kind} deleted and canonically reread.`)})}
  if(loading)return <section className="panel album-loading">Loading canonical Album…</section>; if(!album)return <section className="panel album-editor"><div className="album-error">{error||'Album unavailable.'}</div><button className="ghost-btn" onClick={onClose}>Back</button></section>;
  return <section className="album-editor-stack"><article className="panel album-editor"><div className="album-section-head"><div><span className="eyebrow">CANONICAL ALBUM</span><h3>{album.title}</h3><p><code>{album.id}</code> is immutable. <code>album.trackIds</code> is the only membership/order authority.</p></div><div className="album-editor-actions"><span className={`album-status ${album.status}`}>{badge(album)}</span><button className="ghost-btn compact" onClick={onClose}>Back</button></div></div><div className="album-form-grid"><label><span>Title</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>Type</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as AdminAlbumType})}><option value="album">Album</option><option value="ep">EP</option><option value="collection">Collection</option></select></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AdminAlbumStatus})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label><span>Year</span><input inputMode="numeric" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></label><label><span>Release date</span><input type="date" value={form.releaseDate} onChange={e=>setForm({...form,releaseDate:e.target.value})}/></label><label><span>Editorial heading</span><input value={form.heading} onChange={e=>setForm({...form,heading:e.target.value})}/></label><label className="album-wide"><span>Description</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span>Accent</span><input value={form.accent} onChange={e=>setForm({...form,accent:e.target.value})}/></label><label><span>Accent 2</span><input value={form.accent2} onChange={e=>setForm({...form,accent2:e.target.value})}/></label></div><div className="album-actions"><span>Revision: <code>{album.updatedAt||'missing'}</code></span><button className="primary-btn" disabled={busy||!form.title.trim()} onClick={()=>void saveMetadata()}>Save metadata</button></div></article>
  <article className="panel album-tracklist-panel"><div className="album-section-head"><div><span className="eyebrow">TRACKLIST / MEMBERSHIP</span><h3>{ids.length} ordered tracks</h3><p>Reorder locally, remove from this canonical Album, or move between already-canonical Albums. Track Manager rejects ownership conflicts.</p></div></div><div className="album-boundary-note"><strong>Legacy assignment locked until C2.5-E</strong><span>D1 does not attach existing legacy/Singles tracks to a canonical Album. D2 will bind newly-created tracks through guarded writes; historical migration remains a separate authorized step.</span></div><ol className="album-tracklist">{ids.map((id,i)=><li key={id}><span className="album-track-index">{String(i+1).padStart(2,'0')}</span><div><strong>{byId.get(id)?.title||id}</strong><small>{id}</small></div><div className="album-track-controls"><button disabled={busy||i===0} onClick={()=>{const n=[...ids];[n[i-1],n[i]]=[n[i],n[i-1]];setIds(n)}}>↑</button><button disabled={busy||i===ids.length-1} onClick={()=>{const n=[...ids];[n[i],n[i+1]]=[n[i+1],n[i]];setIds(n)}}>↓</button><button disabled={busy} onClick={()=>setIds(ids.filter(x=>x!==id))}>Remove</button></div><div className="album-track-move"><select value={moves[id]||''} onChange={e=>setMoves({...moves,[id]:e.target.value})}><option value="">Move to…</option>{albums.filter(a=>a.id!==album.id).map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><button disabled={busy||!moves[id]} onClick={()=>void move(id)}>Move</button></div></li>)}</ol><div className="album-actions"><span>{changed?'Unsaved tracklist changes':'Tracklist matches canonical state'}</span><button className="primary-btn" disabled={busy||!changed} onClick={()=>void saveTracklist()}>Save tracklist</button></div></article>
  <article className="panel album-assets-panel"><div className="album-section-head"><div><span className="eyebrow">ALBUM ASSETS</span><h3>Cover + thumbnail</h3><p>Sequential guarded writes only. Studio never writes R2 directly.</p></div></div><div className="album-asset-state"><span className={assets.cover?.present?'present':'missing'}>Cover {assets.cover?.present?'present':'missing'}</span><span className={assets.thumbnail?.present?'present':'missing'}>Thumbnail {assets.thumbnail?.present?'present':'missing'}</span></div><div className="album-cover-workbench"><label className="album-file-input"><span>Choose cover</span><input type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" onChange={e=>setCover(e.target.files?.[0]||null)}/></label>{cover&&<><CoverImagePreview file={cover} alt="Album cover preview"/><CoverPalettePreview palette={palette} editable onChange={setPalette} title="Extracted palette suggestion" note="Nothing is applied automatically."/><button className="ghost-btn compact" disabled={!palette} onClick={()=>palette&&setForm({...form,accent:palette.accent,accent2:palette.accent2})}>Apply palette to metadata form</button></>}</div><div className="album-actions album-asset-actions"><div><button className="ghost-btn" disabled={busy||!assets.cover?.present} onClick={()=>void removeAsset('cover')}>Delete cover</button><button className="ghost-btn" disabled={busy||!assets.thumbnail?.present} onClick={()=>void removeAsset('thumbnail')}>Delete thumbnail</button></div><button className="primary-btn" disabled={busy||!cover} onClick={()=>void upload()}>Upload cover + thumbnail</button></div></article>{notice&&<div className="album-notice">{notice}</div>}{error&&<div className="album-error">{error}</div>}</section>;
}

export function AlbumManager(){
  const [albums,setAlbums]=useState<AdminAlbumSummary[]>([]);const [tracks,setTracks]=useState<StudioTrack[]>([]);const [selected,setSelected]=useState<string|null>(null);const [showCreate,setShowCreate]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  async function load(){setLoading(true);try{const [a,t]=await Promise.all([getAdminAlbums(),getCatalogTracks()]);setAlbums(a.albums||[]);setTracks(t);setError(null)}catch(x){setError(err(x))}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
  const totals=useMemo(()=>({total:albums.length,draft:albums.filter(a=>a.status==='draft').length,tracks:albums.reduce((n,a)=>n+a.trackIds.length,0)}),[albums]);
  if(selected)return <section className="album-manager"><AlbumEditor albumId={selected} albums={albums} tracks={tracks} onChanged={load} onClose={()=>setSelected(null)}/></section>;
  return <section className="album-manager"><div className="catalog-heading album-manager-heading"><div><span className="eyebrow">CATALOG / ALBUMS & PROJECTS</span><h2>Canonical releases, finally managed in Studio.</h2><p>R2 Album manifests are authoritative. Legacy LaunchPAD presentations remain untouched until C2.5-E/F.</p></div><div className="catalog-heading-actions"><div className="catalog-kpis"><div><strong>{totals.total}</strong><span>canonical</span></div><div><strong>{totals.draft}</strong><span>drafts</span></div><div><strong>{totals.tracks}</strong><span>track refs</span></div></div><button className="primary-btn" disabled={loading||Boolean(error)} onClick={()=>setShowCreate(true)}>+ New Album / EP</button></div></div><div className="album-boundary-note panel"><strong>C2.5-D boundary</strong><span>This screen uses Track Manager v5.17. It does not migrate Neon Heartbreaks, Coal to Diamond, Love Letters from Saigon or Singles, and does not remove the LaunchPAD fallback.</span></div>{showCreate&&<AlbumCreatePanel onCancel={()=>setShowCreate(false)} onCreated={async id=>{await load();setShowCreate(false);setSelected(id)}}/>}{loading&&<div className="catalog-message panel">Loading canonical Albums…</div>}{!loading&&error&&<div className="album-error panel"><strong>Album Management unavailable</strong><span>{error}</span><button className="ghost-btn compact" onClick={()=>void load()}>Retry</button></div>}{!loading&&!error&&albums.length===0&&<div className="album-empty panel"><strong>No canonical Album exists yet.</strong><span>Expected before C2.5-E migration. You may create a new draft without touching legacy Albums.</span></div>}{!loading&&!error&&albums.length>0&&<div className="album-grid">{albums.map(a=><button className="panel album-card" key={a.id} onClick={()=>setSelected(a.id)}><div className="album-card-cover"><span>{a.title.slice(0,2).toUpperCase()}</span></div><div className="album-card-body"><div><strong>{a.title}</strong><small>{a.id}</small></div><span className={`album-status ${a.status}`}>{badge(a)}</span><div className="album-card-meta"><span>{a.trackIds.length} tracks</span><span>{a.releaseDate?.slice(0,10)||a.year||'Date TBD'}</span><span>{a.assetState?.cover?.present?'Cover ready':'Cover missing'}</span></div></div></button>)}</div>}</section>;
}
