export const FINDING_LABELS: Record<string, string> = {
  MISSING_ISRC: 'ISRC missing', INVALID_ISRC: 'ISRC format needs review', DUPLICATE_ISRC: 'ISRC shared by separate source recordings',
  DUPLICATE_UPC: 'UPC shared by separate releases', INVALID_UPC: 'UPC/EAN format needs review', AMBIGUOUS_RECORDING_TITLE: 'Similar recording titles remain separate',
  POSSIBLE_RELEASE_OVERLAP: 'Similar release titles remain separate', RELEASE_COUNT_CONFLICT: 'Release counts disagree',
  ISRC_CONTRADICTION: 'Appearance and recording ISRC evidence disagree', ISRC_FLAG_CONFLICT: 'Source ISRC flag disagrees with code',
  UNREVIEWED_TRACK_BINDING: 'Proposed Studio link held for human review', SOURCE_REVIEW_REQUIRED: 'Source requests human review',
  PUBLICATION_UNVERIFIED: 'Current channel availability is unknown', AMUSE_PENDING_REVIEW: 'Amuse candidate remains unverified',
  CHANNEL_OBSERVATION_UNVERIFIED: 'SoundCloud observation is historical', SOURCE_QA_PENDING: 'Source QA remains pending',
  CHANNEL_EVIDENCE_CONFLICT: 'Channel observations disagree',
  RELEASE_METADATA_CONFLICT: 'Duplicate release identity has conflicting metadata',
  DERIVED_SOURCE_COVERAGE_INCOMPLETE: 'Workbook evidence is not fully retained in this derived JSON', UNBOUND_APPEARANCE: 'Appearance has no recording binding',
  MALFORMED_JSON: 'The file is not valid JSON', UNSUPPORTED_SCHEMA: 'Unsupported source schema/version', INVALID_ROOT: 'Source metadata or tables are invalid',
  INVALID_ROW: 'Required fields or field types are invalid', DUPLICATE_ID: 'Duplicate source identity', DUPLICATE_RELEASE_IDENTITY: 'Duplicate release source identity',
  POSITION_OWNERSHIP_CONFLICT: 'Two appearances claim the same release position', ORPHAN_APPEARANCE: 'Appearance references a missing entity',
  ORPHAN_CANDIDATE: 'Candidate references a missing entity', ORPHAN_OBSERVATION: 'Observation references a missing recording',
  SOURCE_COUNT_CONFLICT: 'Source sheet count disagrees with data', PROVENANCE_CONFLICT: 'Recording provenance disagrees with identity',
  FILE_TOO_LARGE: 'File exceeds the 10 MiB limit', TOO_MANY_ROWS: 'File exceeds the 50,000-row limit', JSON_ONLY: 'Select a JSON file',
  UNREADABLE_SOURCE: 'File could not be read as UTF-8', LOCAL_PARSER_FAILED: 'Local parser could not complete', INVALID_INPUT_DIGEST: 'Input fingerprint could not be verified',
};
